"""initial schema

Revision ID: a4fe3c90fb76
Revises: 
Create Date: 2026-06-16 15:38:54.754859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4fe3c90fb76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'GUARDIAN', 'OPERATOR', name='role', native_enum=False), nullable=False),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH_PROFILE', 'INFORMATICS', name='subject', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('spec_year', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_subject'), 'topics', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'GUARDIAN', 'OPERATOR', name='role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('week_label', sa.String(length=80), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_sets_student_id'), 'audit_sets', ['student_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH_PROFILE', 'INFORMATICS', name='subject', native_enum=False), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'DONE', 'REPEAT', 'SKIPPED', name='missionstatus', native_enum=False), nullable=False),
    sa.Column('ai_policy', sa.Enum('ATTEMPT_FIRST', 'BLOCKED', 'ALLOWED_AFTER_ATTEMPT', name='aipolicy', native_enum=False), nullable=False),
    sa.Column('threshold_percent', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('timebox_minutes', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_due_date'), 'missions', ['due_date'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_index(op.f('ix_missions_subject'), 'missions', ['subject'], unique=False)
    op.create_table('subject_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH_PROFILE', 'INFORMATICS', name='subject', native_enum=False), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('target_score', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject', name='uq_subject_track')
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('TEXT', 'CODE', 'PHOTO', 'MIXED', name='attemptkind', native_enum=False), nullable=False),
    sa.Column('mode', sa.Enum('CLEAN_SHEET', 'WITH_HINT', 'UNKNOWN', name='attemptmode', native_enum=False), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('code_text', sa.Text(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_mission_id'), 'attempts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_attempts_submitted_at'), 'attempts', ['submitted_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'NEEDS_MANUAL_REVIEW', name='evidencestatus', native_enum=False), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('error_category', sa.Enum('ARITHMETIC', 'SIGN_TRANSFER', 'ODZ_LOGIC', 'CONDITION_READING', 'PROBABILITY_DOUBLE_COUNT', 'UNKNOWN_METHOD', 'ALGORITHM_LOGIC', 'CODE_SYNTAX', 'CODE_ALGORITHM', 'TIME_MANAGEMENT', 'NONE', 'OTHER', name='errorcategory', native_enum=False), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('rubric_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_attempt_id'), 'evidence', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_error_category'), 'evidence', ['error_category'], unique=False)
    op.create_index(op.f('ix_evidence_mission_id'), 'evidence', ['mission_id'], unique=False)
    op.create_index(op.f('ix_evidence_student_id'), 'evidence', ['student_id'], unique=False)
    op.create_table('error_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('MATH_PROFILE', 'INFORMATICS', name='subject', native_enum=False), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ARITHMETIC', 'SIGN_TRANSFER', 'ODZ_LOGIC', 'CONDITION_READING', 'PROBABILITY_DOUBLE_COUNT', 'UNKNOWN_METHOD', 'ALGORITHM_LOGIC', 'CODE_SYNTAX', 'CODE_ALGORITHM', 'TIME_MANAGEMENT', 'NONE', 'OTHER', name='errorcategory', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_category'), 'error_events', ['category'], unique=False)
    op.create_index(op.f('ix_error_events_created_at'), 'error_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_events_student_id'), 'error_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_error_events_subject'), 'error_events', ['subject'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DUE', 'DONE', 'BACK_TO_WORK', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_due_date'), 'review_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    op.create_index(op.f('ix_review_items_student_id'), 'review_items', ['student_id'], unique=False)
    op.create_index(op.f('ix_review_items_topic_id'), 'review_items', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_topic_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_student_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_due_date'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_error_events_subject'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_student_id'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_created_at'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_category'), table_name='error_events')
    op.drop_table('error_events')
    op.drop_index(op.f('ix_evidence_student_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_mission_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_error_category'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_attempt_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_attempts_submitted_at'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_mission_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('subject_tracks')
    op.drop_index(op.f('ix_missions_subject'), table_name='missions')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_due_date'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_audit_sets_student_id'), table_name='audit_sets')
    op.drop_table('audit_sets')
    op.drop_table('student_profiles')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_subject'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
